# Ejercicio Final
### Zabdiel Emilio Moreno Mendoza
### Catalogo

pclase – Tipo de Boleto, e.g 1 = 1ra, 2 = 2da, 3 = 3ra
survival – Sí la persona sobrevivió o no el accidente (1|0)
name – Nombre del pasajero y titulo incluido
sex – Género del pasajero: female|male
age – Edad en años
sibsp – Número de parientes/cónyuges abordo del Titanic
parch – Número de padres/hijos abordo del Titanic
ticket – Número de Boleto
fare – Costo del boleto
cabin – Número cabina
embarked – Puerto de embarcación (C = Cherburgo; Q = Queenstown; S = Southampton)
boat - Número de bote salvavidas, si tomó alguno
body - Número de cuerpo (si no sobrevivió y se recuperó el cuerpo)
home.dest - Origen y destino del pasajero

### Limpieza de datos
1. Si la edad es null (na) llenar el campo con la media de la edad (usar el metodo fillna())
2. Si embarqued es na llenar con S
3. Cambiar los valores alfanumericos de sex a numero usando { 'female': 1, 'male': 0 }
4. Cambiar los valores alfanumericos de embarked a numero usando { 'S': 0, 'C': 1, 'Q': 2 }
5. Crear una nueva variable llamada child con valor 1 para los pasajeros con una edad menor a 16 años y 0 si el pasajero tiene 16 años o mas
6. Eliminar las columnas ticket, cabin y name
7. Validar que no existan registros duplicados
8. Listar los valores unicos del campo sex
9. Quitar los espacios vacios de los campos que no sean numericos
10. Guardar los datos limpios en un archivos json orientado a registros llamado iniciales_titanic_clean.json (sus iniciales)


https://raw.githubusercontent.com/omarmendoza564/datos/main/datos/titanic.csv


In [1]:
import pandas as pd
import numpy as np

In [2]:
#Leer el archivo csv
mi_df = pd.read_csv('https://raw.githubusercontent.com/omarmendoza564/datos/main/datos/titanic.csv')
mi_df

pclass  survived                                             name  \
0        1.0       1.0                    Allen, Miss. Elisabeth Walton   
1        1.0       1.0                   Allison, Master. Hudson Trevor   
2        1.0       0.0                     Allison, Miss. Helen Loraine   
3        1.0       0.0             Allison, Mr. Hudson Joshua Creighton   
4        1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1305     3.0       0.0                            Zabour, Miss. Thamine   
1306     3.0       0.0                        Zakarian, Mr. Mapriededer   
1307     3.0       0.0                              Zakarian, Mr. Ortin   
1308     3.0       0.0                               Zimmerman, Mr. Leo   
1309     NaN       NaN                                              NaN   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000    0.0    0.0   24160  211.3375       B5        S    2   
1       male   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11   
2     female   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1305  female      NaN    1.0    0.0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000    0.0    0.0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000    0.0    0.0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000    0.0    0.0  315082    7.8750      NaN        S  NaN   
1309     NaN      NaN    NaN    NaN     NaN       NaN      NaN      NaN  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  
1309    NaN                              NaN  

[1310 rows x 14 columns]

In [3]:
#Cuantos NaN existen por columna
mi_df.isnull().sum()

pclass          1
survived        1
name            1
sex             1
age           264
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

In [4]:
#Cambiar datos NaN de la columna edad por el promedio y observar cambios
mi_df['age'].fillna((mi_df['age'].mean()),inplace= True)
mi_df.isnull().sum()

pclass          1
survived        1
name            1
sex             1
age             0
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

In [5]:
#Cambiar datos NaN de la columna embarked
mi_df['embarked'].fillna(value='S',inplace= True)
mi_df.isnull().sum()

pclass          1
survived        1
name            1
sex             1
age             0
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        0
boat          824
body         1189
home.dest     565
dtype: int64

In [6]:
#Cambiamos los datos de la columna sex usando el diccionario { 'female': 1, 'male': 0 } y usamos unique para verificar resultados
mi_df['sex'] = mi_df['sex'].replace({ 'female': 1, 'male': 0 })
mi_df['sex'].unique()

array([ 1.,  0., nan])

In [7]:
#Cambiamos los datos de la columna embarked usando el diccionario { 'S': 0, 'C': 1, 'Q': 2 }
mi_df['embarked'] = mi_df['embarked'].replace({ 'S': 0, 'C': 1, 'Q': 2 })
mi_df['embarked'].unique()

array([0, 1, 2], dtype=int64)

In [8]:
#Creamos la columna child que obtiene datos segun la edad 
edad_rango = [0, 16, np.inf]
edad_etiqueta = [1, 0]
mi_df['child'] = pd.cut(mi_df['age'], 
                            bins =edad_rango, 
                            labels=edad_etiqueta)
mi_df[['age','child']]

age child
0     29.000000     0
1      0.916700     1
2      2.000000     1
3     30.000000     0
4     25.000000     0
...         ...   ...
1305  29.881135     0
1306  26.500000     0
1307  27.000000     0
1308  29.000000     0
1309  29.881135     0

[1310 rows x 2 columns]

In [9]:
#Eliminar las columnas ticket, cabin y name
mi_df.drop(['ticket', 'cabin' , 'name'], axis = 1, inplace = True )
mi_df

pclass  survived  sex        age  sibsp  parch      fare  embarked boat  \
0        1.0       1.0  1.0  29.000000    0.0    0.0  211.3375         0    2   
1        1.0       1.0  0.0   0.916700    1.0    2.0  151.5500         0   11   
2        1.0       0.0  1.0   2.000000    1.0    2.0  151.5500         0  NaN   
3        1.0       0.0  0.0  30.000000    1.0    2.0  151.5500         0  NaN   
4        1.0       0.0  1.0  25.000000    1.0    2.0  151.5500         0  NaN   
...      ...       ...  ...        ...    ...    ...       ...       ...  ...   
1305     3.0       0.0  1.0  29.881135    1.0    0.0   14.4542         1  NaN   
1306     3.0       0.0  0.0  26.500000    0.0    0.0    7.2250         1  NaN   
1307     3.0       0.0  0.0  27.000000    0.0    0.0    7.2250         1  NaN   
1308     3.0       0.0  0.0  29.000000    0.0    0.0    7.8750         0  NaN   
1309     NaN       NaN  NaN  29.881135    NaN    NaN       NaN         0  NaN   

       body                        home.dest child  
0       NaN                     St Louis, MO     0  
1       NaN  Montreal, PQ / Chesterville, ON     1  
2       NaN  Montreal, PQ / Chesterville, ON     1  
3     135.0  Montreal, PQ / Chesterville, ON     0  
4       NaN  Montreal, PQ / Chesterville, ON     0  
...     ...                              ...   ...  
1305    NaN                              NaN     0  
1306  304.0                              NaN     0  
1307    NaN                              NaN     0  
1308    NaN                              NaN     0  
1309    NaN                              NaN     0  

[1310 rows x 12 columns]

In [10]:
#Validar que no existan duplicados
mi_df_dup = mi_df.duplicated()
mi_df[mi_df_dup]

pclass  survived  sex        age  sibsp  parch     fare  embarked boat  \
357      2.0       0.0  0.0  42.000000    0.0    0.0  13.0000         0  NaN   
384      2.0       0.0  0.0  29.881135    0.0    0.0   0.0000         0  NaN   
410      2.0       0.0  0.0  29.881135    0.0    0.0   0.0000         0  NaN   
420      2.0       0.0  0.0  21.000000    1.0    0.0  11.5000         0  NaN   
438      2.0       1.0  1.0  24.000000    1.0    2.0  65.0000         0    9   
...      ...       ...  ...        ...    ...    ...      ...       ...  ...   
1292     3.0       0.0  0.0  29.881135    0.0    0.0   7.5500         0  NaN   
1293     3.0       0.0  0.0  29.881135    0.0    0.0   8.0500         0  NaN   
1297     3.0       0.0  0.0  29.881135    0.0    0.0   7.2500         0  NaN   
1302     3.0       0.0  0.0  29.881135    0.0    0.0   7.2250         1  NaN   
1305     3.0       0.0  1.0  29.881135    1.0    0.0  14.4542         1  NaN   

      body                     home.dest child  
357    NaN                        London     0  
384    NaN                       Belfast     0  
410    NaN                       Belfast     0  
420    NaN         Cornwall / Camden, NJ     0  
438    NaN  Somerset / Bernardsville, NJ     0  
...    ...                           ...   ...  
1292   NaN                           NaN     0  
1293   NaN                           NaN     0  
1297   NaN                           NaN     0  
1302   NaN                           NaN     0  
1305   NaN                           NaN     0  

[117 rows x 12 columns]

In [11]:
#Borramos registros duplicados 
mi_df.drop_duplicates(inplace = True)
mi_df.count()

pclass       1192
survived     1192
sex          1192
age          1193
sibsp        1192
parch        1192
fare         1191
embarked     1193
boat          475
body          121
home.dest     734
child        1193
dtype: int64

In [12]:
#Ya no hay registros duplicados
mi_df[mi_df.duplicated()]

Empty DataFrame
Columns: [pclass, survived, sex, age, sibsp, parch, fare, embarked, boat, body, home.dest, child]
Index: []

In [13]:
#Listar campos unicos del campo sex
mi_df['sex'].unique()

array([ 1.,  0., nan])

In [14]:
mi_df

pclass  survived  sex        age  sibsp  parch      fare  embarked boat  \
0        1.0       1.0  1.0  29.000000    0.0    0.0  211.3375         0    2   
1        1.0       1.0  0.0   0.916700    1.0    2.0  151.5500         0   11   
2        1.0       0.0  1.0   2.000000    1.0    2.0  151.5500         0  NaN   
3        1.0       0.0  0.0  30.000000    1.0    2.0  151.5500         0  NaN   
4        1.0       0.0  1.0  25.000000    1.0    2.0  151.5500         0  NaN   
...      ...       ...  ...        ...    ...    ...       ...       ...  ...   
1304     3.0       0.0  1.0  14.500000    1.0    0.0   14.4542         1  NaN   
1306     3.0       0.0  0.0  26.500000    0.0    0.0    7.2250         1  NaN   
1307     3.0       0.0  0.0  27.000000    0.0    0.0    7.2250         1  NaN   
1308     3.0       0.0  0.0  29.000000    0.0    0.0    7.8750         0  NaN   
1309     NaN       NaN  NaN  29.881135    NaN    NaN       NaN         0  NaN   

       body                        home.dest child  
0       NaN                     St Louis, MO     0  
1       NaN  Montreal, PQ / Chesterville, ON     1  
2       NaN  Montreal, PQ / Chesterville, ON     1  
3     135.0  Montreal, PQ / Chesterville, ON     0  
4       NaN  Montreal, PQ / Chesterville, ON     0  
...     ...                              ...   ...  
1304  328.0                              NaN     1  
1306  304.0                              NaN     0  
1307    NaN                              NaN     0  
1308    NaN                              NaN     0  
1309    NaN                              NaN     0  

[1193 rows x 12 columns]

In [15]:
#Quitar espacios en blancos de campos no numericos
mi_df['home.dest'] = mi_df['home.dest'].str.strip()
mi_df

pclass  survived  sex        age  sibsp  parch      fare  embarked boat  \
0        1.0       1.0  1.0  29.000000    0.0    0.0  211.3375         0    2   
1        1.0       1.0  0.0   0.916700    1.0    2.0  151.5500         0   11   
2        1.0       0.0  1.0   2.000000    1.0    2.0  151.5500         0  NaN   
3        1.0       0.0  0.0  30.000000    1.0    2.0  151.5500         0  NaN   
4        1.0       0.0  1.0  25.000000    1.0    2.0  151.5500         0  NaN   
...      ...       ...  ...        ...    ...    ...       ...       ...  ...   
1304     3.0       0.0  1.0  14.500000    1.0    0.0   14.4542         1  NaN   
1306     3.0       0.0  0.0  26.500000    0.0    0.0    7.2250         1  NaN   
1307     3.0       0.0  0.0  27.000000    0.0    0.0    7.2250         1  NaN   
1308     3.0       0.0  0.0  29.000000    0.0    0.0    7.8750         0  NaN   
1309     NaN       NaN  NaN  29.881135    NaN    NaN       NaN         0  NaN   

       body                        home.dest child  
0       NaN                     St Louis, MO     0  
1       NaN  Montreal, PQ / Chesterville, ON     1  
2       NaN  Montreal, PQ / Chesterville, ON     1  
3     135.0  Montreal, PQ / Chesterville, ON     0  
4       NaN  Montreal, PQ / Chesterville, ON     0  
...     ...                              ...   ...  
1304  328.0                              NaN     1  
1306  304.0                              NaN     0  
1307    NaN                              NaN     0  
1308    NaN                              NaN     0  
1309    NaN                              NaN     0  

[1193 rows x 12 columns]

In [18]:
#Guardar datos limpios en un archivo json orientado a registros
mi_df.to_json('ZEMM_titanic_clean.json',orient='records')